### ISSUE TITLE
[BUG] Detected blocking call to open with args ('scenes.yaml')

### ISSUE THREAD

**Issue by owpac** [hugobloem/stateful_scenes#105]
Hello, a bug of Stateful Scenes occur since the new version of HA ([2024.7.3](https://github.com/home-assistant/core/releases/tag/2024.7.3))

I don't really get why and how there is a problem, but it seems there is a solution [here](https://github.com/StephanJoubert/home_assistant_solarman/issues/617) 

```yaml
2024-07-24 18:27:12.995 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('scenes.yaml',) inside the event loop by custom integration 'stateful_scenes' at custom_components/stateful_scenes/StatefulScenes.py, line 76: with open(self.scene_path, encoding="utf-8") as f: (offender: /config/custom_components/stateful_scenes/StatefulScenes.py, line 76: with open(self.scene_path, encoding="utf-8") as f:), please create a bug report at https://github.com/hugobloem/stateful_scenes/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 451, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/stateful_scenes/__init__.py", line 22, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id] = Hub(
  File "/config/custom_components/stateful_scenes/StatefulScenes.py", line 55, in __init__
    scene_confs = self.load_scenes()
  File "/config/custom_components/stateful_scenes/StatefulScenes.py", line 76, in load_scenes
    with open(self.scene_path, encoding="utf-8") as f:
```

**Comment by owpac** [comment]
Hey @hugobloem, sorry to ping you, did you have time to check this issue? It's still broken for the recent version of HA.

**Comment by hugobloem** [comment]
Hi, I should have some time this week to work on this project again. I will have a look at this issue as well.

**Comment by pgale** [comment]
Are you going to be able to look at the Hue integration too?

**Comment by hugobloem** [comment]
Yes I will look at that too 😊
