### ISSUE TITLE
Problem with 0.3.0

### ISSUE THREAD

**Issue by vsmith80** [hugobloem/stateful_scenes#9]
In 0.3.0 i have no switching worked.
It's home-assistant.log

`2023-09-21 11:15:08.793 ERROR (MainThread) [homeassistant.components.switch] Error while setting up stateful_scenes platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stateful_scenes/switch.py", line 51, in setup_platform
    hub = StatefulScenes.Hub(hass, scene_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stateful_scenes/StatefulScenes.py", line 23, in __init__
    scene_confs = self.load_scenes()
                  ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stateful_scenes/StatefulScenes.py", line 36, in load_scenes
    scenes_confs = yaml.load(f, Loader=yaml.FullLoader)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.11/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.11/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.11/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 495: ordinal not in range(128)`

I've just checked 0.2.0 release and found that in 0.2.0 in StatefulScenes.py and found some change in **def load_scenes(self)** :

`class Hub:
    """State scene class."""

    def __init__(
        self, hass: HomeAssistant, scene_path: str, number_tolerance=1
    ) -> None:
        """Initialize."""
        self.scene_path = scene_path
        self.number_tolerance = number_tolerance
        self.hass = hass
        self.scenes = []

        self.load_scenes()

    def load_scenes(self) -> bool:
        with open(self.scene_path, "r") as f:
            scenes_confs = yaml.load(f, Loader=yaml.FullLoader)
`

And in 0.3.0 in same file

`class Hub:
    """State scene class."""

    def __init__(
        self, hass: HomeAssistant, scene_path: str, number_tolerance=1
    ) -> None:
        """Initialize."""
        self.scene_path = scene_path
        self.number_tolerance = number_tolerance
        self.hass = hass
        self.scenes = []

        scene_confs = self.load_scenes()
        for scene_conf in scene_confs:
            self.scenes.append(
                Scene(
                    self.hass,
                    self.extract_scene_configuration(scene_conf),
                    self.number_tolerance,
                )
            )

    def load_scenes(self) -> list:
        """Load scenes from yaml file."""
        with open(self.scene_path, encoding="ascii") as f:
            scenes_confs = yaml.load(f, Loader=yaml.FullLoader)
`
So, when i made open(self.scene_path, "r") arguments, like it was in 0.2.0 -  it started.

And some lines appears in logs after restart 
` ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stateful_scenes/StatefulScenes.py", line 122, in update_callback
    self.schedule_update(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 876, in schedule_update_ha_state
    self.hass.create_task(
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_task'
2023-09-21 11:36:48.722 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
`

But it looks like it works.

**Comment by hugobloem** [comment]
Hi, thanks for bringing this up. 

I added the encoding because otherwise pylint would complain about no encoding being specified.  I will change this back as it seems to have impacted the loading. 

I'll update today or tomorrow. 

Cheers,
Hugo

**Comment by vsmith80** [comment]
Thaks a lot! It's great integration, so i'm sad when it's not working )

**Comment by hugobloem** [comment]
Please try and see whether 0.3.1 fixes your issue.

**Comment by vsmith80** [comment]
Thanks a lot! looks like it works!
