### ISSUE TITLE
1.3.0b5 issues on Hue

### ISSUE THREAD

**Issue by pgale** [hugobloem/stateful_scenes#97]
Hi,
I've now setup and tested b5. ~~The good news is no more errors in the log like I had before~~. However, I get inconsistent behaviour:

1) Turning a scene on will turn on the stateful scene about 4 out of 5 times, so not always.
2) Once the scene is activated, it will deactivate between 2 seconds to 60 seconds later.

I have Three Hue scenes setup in Stateful Scenes with 9 lamps in the scene. There are additional group entries that cover combinations of lamps e.g. my ceiling light is made up of three lamps and the way the Hue integration imports them, it sets up a group called 'ceiling light'. I'm not sure if this makes a difference as I only added the actual lamps, not the groups.

I have tried debounce time of 0.5, 1 and 1.5 seconds - no difference. Restore on deactivate is OFF for all. Transit time is 1 sec for all.

Stateful scene will always turn off. I have these scenes controlled via Blacky's sensor light blueprint but I have also bypassed it, so there shouldn't be anything else affecting the lights. Just watching them, nothing changes that I can see when the Stateful Scene turns off.

Any ideas why it might be deactivating?

Thanks.

**Comment by pgale** [comment]
Oh, just checked again and see these errors (if they are important?):

``Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:744
integration: Switch (documentation, issues)
First occurred: 21:07:31 (12 occurrences)
Last logged: 21:07:31

Platform stateful_scenes does not generate unique IDs. ID 1710954379596_restore_on_deactivate already exists - ignoring switch.study_lights_off_restore_on_deactivate
Platform stateful_scenes does not generate unique IDs. ID stateful_1711116503704 already exists - ignoring switch.living_room_off_stateful_scene
Platform stateful_scenes does not generate unique IDs. ID 1711116503704_restore_on_deactivate already exists - ignoring switch.living_room_off_restore_on_deactivate
Platform stateful_scenes does not generate unique IDs. ID stateful_1712745261109 already exists - ignoring switch.en_suite_off_stateful_scene
Platform stateful_scenes does not generate unique IDs. ID 1712745261109_restore_on_deactivate already exists - ignoring switch.en_suite_off_restore_on_deactivate```

**Comment by pgale** [comment]
and this one just popped up:

```Logger: homeassistant
Source: helpers/entity.py:1230
First occurred: 21:07:45 (29 occurrences)
Last logged: 21:09:38

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/stateful_scenes/StatefulScenes.py", line 316, in update_callback
    self.schedule_update(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1230, in schedule_update_ha_state
    self.hass.create_task(
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_task'```

**Comment by pgale** [comment]
@hugobloem any thoughts on the hue issues?

**Comment by pgale** [comment]
@hugobloem do you think you'll be able to solve this issue or is Hue support a non-starter do you think?

**Comment by simonheng** [comment]
I am having the same issues when testing 1.3.0b5!

**Comment by pgale** [comment]
Not heard from Hugo in some time. Hopefully he'll have some time at some point to get this working.

**Comment by pgale** [comment]
Do you think you'll ever get this working? Might be best to remove Hue support if not.

**Comment by hugobloem** [comment]
Unfortunately, I have never been able to reproduce this issue. With the changes in #113 the callback functions should be internally known to the Scene which should hopefully make it more robust.

**Comment by hugobloem** [comment]
Let me know if this fixes things, please.

**Comment by pgale** [comment]
I'll give it another try.
